services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: timetracker_app
    container_name: timetracker_app
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 123
      DB_NAME: timetracker
    depends_on:
      - db
    networks:
      - timetracker_network

  nginx:
    image: nginx:latest
    container_name: timetracker_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - timetracker_network

  db:
    image: mysql:8.0
    container_name: timetracker_db
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: timetracker
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - timetracker_network

volumes:
  db_data:

networks:
  timetracker_network:
    driver: bridge